title: DaeChi Choi
name: 최대치
email: eocl777@naver.com
description: >-
  Wev Developer


baseurl: ""
url: "https://eocl777.github.io"


# profile 이미지
profile_image: images/me.jpg


# SNS 아이디
# facebook_id: 
instagram_id: cmaximum95


# Youtube vid
youtube_vid: #


# Custom Color
primary: 2c98f0 #b72cf0 #메인 테마 색
primary_hover: 44A4F2 #9a2dc7 #마우스 올릴 때 바뀌는 색

#tech skil color
color_1: 2c98f0 #b72cf0
color_2: ec5453
color_3: f9bf3f
color_4: a84cb8
color_5: 2fa499
color_6: 4054b2


# slider type 0  (텍스트가 우측 정렬된 슬라이더)
slider_0: # 형식에 맞추어 항목 추가
- background_url: images/slider_0.jpg
  title: Welcome <br> To my<br> portfolio<br>
  position: absolute
  transform: translate( -50%, -50% )
  left: -225px
  bottom: 520px


# slider type 1  (텍스트가 좌측 정렬된 슬라이더)
slider_1: # 형식에 맞추어 항목 추가
- background_url: images/img_bg.jpg
  title: JAVA Web<br>Developer
  position: absolute
  transform: translate( -50%, -50% )
  left: 200px
  bottom: -150px
  subtitle: >- 
    JAVA<br>
    JavaScript<br>
    Vue.js<br>
    Spring Framework<br>
    초보 개발자 최대치입니다.

# About
about_meta: About Me
about_header: >- 
  "성장하는 것이 즐거운 개발자"
about_introduce: >-
  "안녕하세요. 웹 개발자를 꿈꾸는 아기 개발자, 최대치입니다"
about_content: >-
  &nbsp;고등학교 시절Make:라는 책을 접하게 되었습니다. 
  아두이노와 코드만 있다면 무엇이든지 만들 수 있다는 메이커들의 다양한 작품들이 소개되어 있는 이 책은 처음으로 SW를 알게 해주었습니다. 
  이 책을 읽고 때로는 누군가를 위해서, 때로는 재미있는 아이디어로 재미를 위해서 <strong>무언가를 만들어 내는 개발자가 되기를 결심하였습니다.</strong> <br>
  &nbsp;개발자는 게임의 캐릭터와 같다고 생각 합니다. 
  끊임 없이 SW세계를 모험하며 레벨 업 하여 성장해 나갑니다. 
  저도 광대한 SW 세계의 개발자가 되어 <strong>끊임 없이 조사하고, 공부하여 끊임 없이 성장해 가는 개발자가 되고 싶습니다.</strong>
about_services: # 형식에 맞추어 항목 추가
- icon: icon-code
  name: JAVA
- icon: icon-monitor
  name: Web
- icon: icon-data
  name: DB
- icon: icon-device-desktop
  name: Serve

about_box_content: 광대한 SW 세계에서 <br> 끊임 없이 레벨 업 하고 모험하는 개발자가 되겠습니다!
about_box_content_color: rgb(255, 255, 255)

about_box_button:
  link: #
  name: 끊임 없이 성장하는 사람이 되겠습니다!


# Tech  skill
tech_meta: TECH SKILLS
tech_header: 저는 현재 이것을 할 수 있습니다.
tech_content: markdown으로 할수 있으면 좋을듯
tech_list: # 형식에 맞추어 항목 추가
- name: Java
  color: color-1
  animation: fadeInLeft
  percent: 70
  mark: 70
  content: 자바 기초, 객체지향을 중점으로 자바 언어의 기본적인 문법에 대해 알고 있으며, 자료구조 및 알고리즘을 자바로 공부하였습니다.
- 
  name: DB
  color: color-2
  animation: fadeInRight
  percent: 50
  mark: 50
  content: MySQL을 통해 관계형 데이터 베이스를 알게 되고 공부하였습니다. 공부한 기간이 길지 않아 더 많이 공부하고 내 것으로 만들겠다고 생각하고 공부 중입니다.
- 
  name: Docker
  color: color-3
  animation: fadeInLeft
  percent: 20
  mark: 25
  content: Docker를 서버로 활용하고, 프로젝트에 적용시키고 싶어  Docker의 기본 지식과 사용방법에 대해 학습하고 있습니다.
- 
  name: Git
  color: color-4
  animation: fadeInRight
  percent: 60
  mark: 60
  content: 대부분의 프로젝트를 gitlab를 통해 소스 코드를 관리하였으나, 삼성 청년 SW 아카데미 전용 gitlab이기에 새로운 개인 github를 통해 학습한 내용(TIL)과 프로젝트를 관리해 나갈 예정입니다.

  # name: Node JS
  # color: color-5
  # animation: fadeInRight
  # percent: 50
  # mark: 50
  # content: 

tech_desc: 웹 개발자로 성장하기 위해 <strong> React, Node JS, AWS, docker </strong>등을 계속해서 조금씩 공부할 생각입니다. 


# Project
project_meta: My Work
project_header: PROJECT
project_introduce: <span>팀 프로젝트</span><span>개인 프로젝트</span>


project_team_name: 팀프로젝트
project_team: # 형식에 맞추어 항목 추가
- background_url: images/team_project1.jpg
  animation: fadeInRight
  name: Happy House(2021.11)
  description: 삼성 SW에서 4개월간 배운 내용들을 활용하여 아파트 정보를 조회하는 웹 페이지를 만들었습니다.
  detail_url: https://youtu.be/jvCmuHbgkuQ
  readmore_url: pdf/happyhouse.pdf

# - background_url: images/blog-1.PNG
#   animation: fadeInLeft
#   name: 개인 프로젝트 어쩌구
#   description: 설명설명 설명 설명
#   detail_url: #
#   readmore_url: #

project_my_name: 개인프로젝트
project_my: # 형식에 맞추어 항목 추가
- background_url: images/my_project.jpg
  animation: fadeInRight
  name: Personal Portfolio(2021.12)
  description: 나를 보여줄 수 있는 포트폴리오를 만들었습니다.
  detail_url: #
  readmore_url: #

# - background_url: images/team_project3.PNG
#   animation: fadeInRight
#   name: sasdasdasdsadsagjghkukt(2020.05)
#   description:
#   detail_url: #
#   readmore_url: #

# project_business_name: Business
# project_business: # 
# - background_url: images/my_business.PNG
#   animation: fadeInTop
#   name: 인프런강의(2021~)
#   description: >-
#     취준과 대학원진학을 동시에 했을때 많은 곳에서 github 주소뿐만아니라 개발 블로그주소도 요청하는데가 많았다.(물론 필수는 아니였지만) 
#     또한 교육기관(멋쟁이사자처럼,네이버 부스트 캠프, 소마등)에서도 마찬가지이다. 현재 프로그래밍의 중요도가 올라가고있으며 초등학생부터 의무교육을 시작한다고 한다. 
#     많은 비전공자들이 뒤늦게 프로그래밍을 시작하고 있다. 열심히 배우고 지원할려니 개발 블로그를 요청한다... 프로그래밍을 시작할때 알았다면 얼마나 좋았을까. 
#     공부하면서 블로그 내용을 채웠으면 참 좋았을것이다. 이런 흐름을 캐치하여 나는 개발자다운 블로그인 깃헙블로그를 만드는 짧은 강의를 만들었다. 
#   detail_url: #
#   readmore_url: #

# 더보기 내용
project_load_more: 앞으로 더 많은 프로젝트가 추가될 예정입니다:)    
project_load_more_url: #


# Experience
exp_meta: What have I achieved?
exp_header: 저는 이런 "경험"들을 해봤습니다.
exp_content: 현재 개발로서는 큰 도움은 되지 않을 수 있지만, 회사에서 필요로 한다면 이런 역량도 가지고 있습니다.
exp_services: # 형식에 맞추어 항목 추가
- name: 친화력
  color: color-1
  icon: icon-bulb
  content: 여러 해외 프로그램에 참여하였습니다. 다양한 문화의 사람들과 만나고 경험하며 친화력을 갖추었습니다.

- name: 기술습득
  color: color-2
  icon: icon-home
  content: 호기심을 가지고 항상 열정을 다해 공부하며 새로운 기술에 대해 성장해 간다는 즐거운 마음으로 배웁니다.

- name: 프로젝트
  color: color-3
  icon: icon-phone3
  content: 많은 프로젝트 경험을 가진 것은 아니지만 기획부터 구현까지 경험하면서 프로젝트의 진행 방식을 배웠습니다. 


exp_counters_bg_img: images/about.jpg
exp_counters:
- name: age
  count: 27
  speed: 5000
- name: project
  count: 2
  speed: 10000



# Education
edu_meta: Education
edu_header: Education
edu_list:
- title: SAMSUNG 청년 SW 아카데미
  subtitle: SSAFY(SAMSUNG SOFTWARE ACADEMY FOR YOUTH) 코딩과정
  date: 2021.07 - 현재
  content: SAMSUNG 청년 SW 아카데미에서 Java, 알고리즘, Vue JS, MySQL 등 다양한 지식을 습득하고 있습니다.

- title: DAEJEON UNIVERSITY
  subtitle: 대전대학교 전자 정보통신공학과 졸업
  date: 2015.03 - 2019.08
  content: 대전대학교 전자 정보통신공학과를 졸업하였습니다.

- title: NAMSUNG HIGH SCHOOL
  subtitle: 남성고등학교
  date: 2011.03 - 2014.02
  content: 남성고등학교 졸업



# Contact
contact_meta: Get in Touch
contact_header: Contact
contact_list:
- title: eocl777@naver.com
  icon: icon-globe-outline
- title: 서울특별시 구로구 구로동
  icon: icon-map
- title: +82 10 6632 1995
  icon: icon-phone
- title: https://github.com/CmaximumSE
  icon: icon-layers2
  url: https://google.com
#contact_message: <em>연락해주셔서 감사합니다.</em> 24시간이내에 회신드리도록 하겠습니다. :)


optional_front_matter:
  remove_originals:    true
